/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.br.ifpr.view;

import edu.br.ifpr.controller.IndexController;

/**
 *
 * @author rafael
 */
public class IndexView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IndexView.class.getName());
    IndexController indexController = new IndexController();

    /**
     * Creates new form IndexView
     */
    public IndexView() {
        initComponents();
        this.setTitle("SGB - Sistema de Gestão para Bibliotecas");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mRegister = new javax.swing.JMenu();
        mIAuthorRegister = new javax.swing.JMenuItem();
        mIBookRegister = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mRegister.setText("Cadastros");

        mIAuthorRegister.setText("Autores");
        mIAuthorRegister.setName(""); // NOI18N
        mIAuthorRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIAuthorRegisterActionPerformed(evt);
            }
        });
        mRegister.add(mIAuthorRegister);

        mIBookRegister.setText("Livros");
        mIBookRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIBookRegisterActionPerformed(evt);
            }
        });
        mRegister.add(mIBookRegister);

        jMenuBar1.add(mRegister);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mIAuthorRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIAuthorRegisterActionPerformed
        indexController.openAuthorView();
    }//GEN-LAST:event_mIAuthorRegisterActionPerformed

    private void mIBookRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIBookRegisterActionPerformed
        indexController.openBookView();
    }//GEN-LAST:event_mIBookRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IndexView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mIAuthorRegister;
    private javax.swing.JMenuItem mIBookRegister;
    private javax.swing.JMenu mRegister;
    // End of variables declaration//GEN-END:variables
}
